### ISSUE TITLE
Gzip dependency problem

### ISSUE THREAD

**Issue by fredrikt** [Yubico/yubikit-swift#1]
Hi

I'm getting the error "No such module 'Gzip'" in PIVSession.swift.

How to reproduce:
1) Create new project "Test", iOS, App
2) File -> Add package dependency, add package using URL https://github.com/Yubico/yubikit-swift/
3) Build project

I tried installing the Gzip package myself, but still got the same error. I'm new to Swift and thought that perhaps it is the YubiKit package that need to depend on Gzip and not my app (Test)?

**Comment by jensutbult** [comment]
Thanks for reporting the issue and testing the new sdk! Ideally you would choose to add the yubikit-swift package with a dependency on the latest release instead of the master branch. After some investigation it seems like SPM don't like pre-releases (which makes sense) so adding a dependency on the 0.1 pre-release will fail. The gzip-issue should be fixed now but be aware that the PIVSession is still work in progress.
